version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbit-data/:/var/lib/rabbitmq/
        - ./rabbit-log/:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 30s
      retries: 5
  
  master:
    build:
      dockerfile: Dockerfile.master
      context: .
    command: "npm run start:master"
    restart: on-failure
    environment: 
      - RABBIT_HOST=rabbitmq

    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build:
      dockerfile: Dockerfile.consumer
      context: .
    command: "npm run start:consumer"
    restart: on-failure
    scale: 3
    environment: 
      - RABBIT_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy